version: '3.8'

services:

  nodejs:
    build:
      context: nodejs
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /usr/share/nginx/frontend
    volumes:
      - ./project:/usr/share/nginx/frontend
    environment:
      - HOST=0.0.0.0
    command: tail -F anything
    user: "${ID_USER}:${ID_GROUP}"
